name: CI/CD avec Docker

on: [push]

jobs:

  # JOB 1 : CI (Reste identique)
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: python test_calculatrice.py

  # JOB 2 : CD (Docker)
  build-push-docker:
    needs: test-app # On attend que les tests soient OK
    runs-on: ubuntu-latest

    # Permission nécessaire pour que le pipeline puisse écrire dans le registre GitHub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Connexion au registre GitHub (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: avocahdoe # Votre nom d'utilisateur GitHub (Automatique)
          password: ${{ secrets.GITHUB_TOKEN }} # Token généré automatiquement par GitHub Action (Pas besoin de le créer)

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construction et Push de l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/avocahdoe/calculatrice:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/calculatrice:latest
